version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_vet
    restart: always
    environment:
      POSTGRES_USER: veterinaria
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: veterinaria_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  pgdata:
